openapi: 3.0.3
info:
  title: User Management Service
  description: API for User Management Service
  version: 1.0.0
paths: {}

components:
  schemas:
    ValidateUserCommand:
      type: object
      properties:
        email:
          type: string
          format: email
        reservationId:
          type: integer
    ValidatedUserEvent:
      type: object
      properties:
        reservationId:
          type: integer
        username:
          type: string
        email:
          type: string
          format: email
        userValid:
          type: boolean
          default: false
