openapi: 3.0.3
info:
  title: Billing Service API
  description: API for Billing Service
  version: 1.0.0
paths:
  /api/v1/bills/user/{userId}:
    get:
      tags:
        - Billing
      summary: Get user bill by ID
      description: Retrieve the bill for a specific user by their ID
      operationId: GetUserBillById
      parameters:
        - in: query
          name: userId
          schema:
            type: integer
          required: true
          description: ID of the user to retrieve the bill
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBill'
        '404':
          description: Bill not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/bills/{id}:
    get:
      tags:
        - Billing
      summary: Get bill by ID
      description: Retrieve bill details by bill ID
      operationId: GetBillById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the bill to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserBill'
        '404':
          description: Bill not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    UserBill:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        carId:
          type: integer
        reservationId:
          type: integer
        amount:
          type: number
        details:
          type: string
        date:
          type: string
          format: date-time
        status:
          type: string
          enum: [PAID, UNPAID]
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '4001'
        message:
          type: string
          description: 'Brief explanation about the error'
