openapi: 3.0.3
info:
  title: Car Listing Service
  description: API for Car Listing Service
  version: 1.0.0
paths:
  /api/v1/addCar:
    post:
      tags:
        - Car Listing
      summary: Add a new car listing
      description: Adds a new car listing to the platform
      operationId: AddCarListing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCarListingCommand'
      responses:
        '201':
          description: Car listing added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCar'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/cars/{carId}:
    get:
      tags:
        - Car Listing
      summary: Get car listing by ID
      description: Retrieve car details by car ID
      operationId: GetCarById
      parameters:
        - in: path
          name: carId
          schema:
            type: integer
          required: true
          description: ID of the car listing to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiCar'
        '404':
          description: Car listing not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    AddCarListingCommand:
      type: object
      properties:
        ownerName:
          type: string
        carModel:
          type: string
        year:
          type: integer
    ApiCar:
      type: object
      properties:
        carId:
          type: integer
        ownerName:
          type: string
        carModel:
          type: string
        year:
          type: integer
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '2001'
        message:
          type: string
          description: 'Brief explanation about the error'
