openapi: 3.0.3
info:
  title: Reservation Service
  description: API for Reservation Service
  version: 1.0.0
paths:
  /api/v1/reservations:
    post:
      tags:
        - Reservation
      summary: Create a new reservation
      description: Creates a reservation for a specific car and timeslot
      operationId: CreateReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReservationCommand'
      responses:
        '201':
          description: Reservation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservation'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservations/{reservationId}:
    get:
      tags:
        - Reservation
      summary: Get reservation by ID
      description: Retrieve reservation details by reservation ID
      operationId: GetReservationById
      parameters:
        - in: path
          name: reservationId
          schema:
            type: integer
          required: true
          description: ID of the reservation to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservation'
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    CreateReservationCommand:
      type: object
      properties:
        carId:
          type: integer
        timeslot:
          type: string
          format: date-time
    ApiReservation:
      type: object
      properties:
        reservationId:
          type: integer
        carId:
          type: integer
        timeslot:
          type: string
          format: date-time
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '3001'
        message:
          type: string
          description: 'Brief explanation about the error'
