openapi: 3.0.3
info:
  title: Reservation Service
  description: API for Reservation Service
  version: 1.0.0
paths:
  /api/v1/reservations:
    post:
      tags:
        - Reservation
      summary: Create a new reservation
      description: Creates a reservation for a specific car and timeslot
      operationId: createReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationCommand'
      responses:
        '201':
          description: Reservation created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservationResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /api/v1/reservations/{reservationId}:
    get:
      tags:
        - Reservation
      summary: Get reservation by ID
      description: Retrieve reservation details by reservation ID
      operationId: getReservationById
      parameters:
        - in: path
          name: reservationId
          schema:
            type: integer
          required: true
          description: ID of the reservation to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmingReservationCommand'
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
  /api/v1/reservations/confirm:
    patch:
      tags:
        - Reservation
      summary: Confirm or decline a reservation
      description: Allows a car owner to confirm or decline a reservation.
      operationId: confirmReservation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmingReservationCommand'
      responses:
        '200':
          description: Reservation confirmation status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiReservation'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
components:
  schemas:
    FinalisingReservationCommand:
      type: object
      properties:
        reservationId:
          type: integer
        userEmail:
          type: string
          format: email
        carId:
          type: integer
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    ConfirmingReservationCommand:
      type: object
      properties:
        reservationId:
          type: integer
        ownerEmail:
          type: string
          format: email
        accepted:
          type: boolean
    ReservationCommand:
      type: object
      properties:
        userEmail:
          type: string
          format: email
        carId:
          type: integer
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    ApiReservationResponse:
      type: object
      properties:
        reservationId:
          type: integer


    ApiReservation:
      type: object
      properties:
        reservationId:
          type: integer
        userEmail:
          type: string
          format: email
        carId:
          type: integer
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '3001'
        message:
          type: string
          description: 'Brief explanation about the error'