openapi: 3.0.3
info:
  title: Notification Service v1
  description: API for Notification Service
  version: 1.0.11
paths: {}
components:
  schemas:
    SendEmailCommand:
      type: object
      properties:
        recipient:
          type: string
        message:
          type: string