openapi: 3.0.3
info:
  title: Billing Service API
  description: API for Billing Service
  version: 1.0.0
paths: {}

components:
  schemas:
    ReverseBillingCommand:
      type: object
      properties:
        billId:
          type: integer
        userEmail:
          type: string
          format: email
        reservationId:
          type: integer
    BilledUserEvent:
      type: object
      properties:
        billId:
          type: integer
        userEmail:
          type: string
          format: email
        billAmount:
          type: number
        reservationId:
          type: integer
    BillCommand:
      type: object
      properties:
        reservationId:
          type: integer
        userEmail:
          type: string
          format: email
        dueDate:
          type: string
          format: date-time
        amount:
          type: number
        amountDays:
          type: integer
    ApiBill:
      type: object
      properties:
        billId:
          type: integer
        userEmail:
          type: string
          format: email
        carId:
          type: integer
        reservationId:
          type: integer
        amount:
          type: number
        issuedDate:
          type: string
          format: date-time
        dueDate:
          type: string
          format: date-time
        status:
          type: string
          enum: [PAID, UNPAID, OVERDUE]
    ApiError:
      type: object
      properties:
        code:
          type: string
          description: 'Functional code specifying the error'
          example: '4001'
        message:
          type: string
          description: 'Brief explanation about the error'
